// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewsItem struct {
	ID          string `json:"id"`
	Headline    string `json:"headline"`
	Resume      string `json:"resume"`
	Link        string `json:"link"`
	ExtractedAt string `json:"extracted_at"`
	CreatedAt   string `json:"created_at"`
}
